import type { GenesysRegion } from "./types";

const now = "";

export const DEFAULT_ACTIVE_REGION_ID = "apse1";

export const SYSTEM_GENESYS_REGIONS: GenesysRegion[] = [
  {
    id: "use1",
    name: "Americas (US East - N. Virginia)",
    domain: "mypurecloud.com",
    applicationUrl: "https://apps.mypurecloud.com",
    apiBaseUrl: "https://api.mypurecloud.com",
    authBaseUrl: "https://login.mypurecloud.com",
    defaultApplicationUrl: "https://apps.mypurecloud.com",
    defaultApiBaseUrl: "https://api.mypurecloud.com",
    defaultAuthBaseUrl: "https://login.mypurecloud.com",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "usw2",
    name: "Americas (US West - Oregon)",
    domain: "usw2.pure.cloud",
    applicationUrl: "https://apps.usw2.pure.cloud",
    apiBaseUrl: "https://api.usw2.pure.cloud",
    authBaseUrl: "https://login.usw2.pure.cloud",
    defaultApplicationUrl: "https://apps.usw2.pure.cloud",
    defaultApiBaseUrl: "https://api.usw2.pure.cloud",
    defaultAuthBaseUrl: "https://login.usw2.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "cac1",
    name: "Americas (Canada - Central)",
    domain: "cac1.pure.cloud",
    applicationUrl: "https://apps.cac1.pure.cloud",
    apiBaseUrl: "https://api.cac1.pure.cloud",
    authBaseUrl: "https://login.cac1.pure.cloud",
    defaultApplicationUrl: "https://apps.cac1.pure.cloud",
    defaultApiBaseUrl: "https://api.cac1.pure.cloud",
    defaultAuthBaseUrl: "https://login.cac1.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "mxc1",
    name: "Americas (Mexico - Central)",
    domain: "mxc1.pure.cloud",
    applicationUrl: "https://apps.mxc1.pure.cloud",
    apiBaseUrl: "https://api.mxc1.pure.cloud",
    authBaseUrl: "https://login.mxc1.pure.cloud",
    defaultApplicationUrl: "https://apps.mxc1.pure.cloud",
    defaultApiBaseUrl: "https://api.mxc1.pure.cloud",
    defaultAuthBaseUrl: "https://login.mxc1.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "sae1",
    name: "Americas (São Paulo)",
    domain: "sae1.pure.cloud",
    applicationUrl: "https://apps.sae1.pure.cloud",
    apiBaseUrl: "https://api.sae1.pure.cloud",
    authBaseUrl: "https://login.sae1.pure.cloud",
    defaultApplicationUrl: "https://apps.sae1.pure.cloud",
    defaultApiBaseUrl: "https://api.sae1.pure.cloud",
    defaultAuthBaseUrl: "https://login.sae1.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "apse1",
    name: "Asia Pacific (Singapore)",
    domain: "apse1.pure.cloud",
    applicationUrl: "https://apps.apse1.pure.cloud",
    apiBaseUrl: "https://api.apse1.pure.cloud",
    authBaseUrl: "https://login.apse1.pure.cloud",
    defaultApplicationUrl: "https://apps.apse1.pure.cloud",
    defaultApiBaseUrl: "https://api.apse1.pure.cloud",
    defaultAuthBaseUrl: "https://login.apse1.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "apse2",
    name: "Asia Pacific (Sydney)",
    domain: "mypurecloud.com.au",
    applicationUrl: "https://apps.mypurecloud.com.au",
    apiBaseUrl: "https://api.mypurecloud.com.au",
    authBaseUrl: "https://login.mypurecloud.com.au",
    defaultApplicationUrl: "https://apps.mypurecloud.com.au",
    defaultApiBaseUrl: "https://api.mypurecloud.com.au",
    defaultAuthBaseUrl: "https://login.mypurecloud.com.au",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "apne1",
    name: "Asia Pacific (Tokyo)",
    domain: "mypurecloud.jp",
    applicationUrl: "https://apps.mypurecloud.jp",
    apiBaseUrl: "https://api.mypurecloud.jp",
    authBaseUrl: "https://login.mypurecloud.jp",
    defaultApplicationUrl: "https://apps.mypurecloud.jp",
    defaultApiBaseUrl: "https://api.mypurecloud.jp",
    defaultAuthBaseUrl: "https://login.mypurecloud.jp",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "apne2",
    name: "Asia Pacific (Seoul)",
    domain: "apne2.pure.cloud",
    applicationUrl: "https://apps.apne2.pure.cloud",
    apiBaseUrl: "https://api.apne2.pure.cloud",
    authBaseUrl: "https://login.apne2.pure.cloud",
    defaultApplicationUrl: "https://apps.apne2.pure.cloud",
    defaultApiBaseUrl: "https://api.apne2.pure.cloud",
    defaultAuthBaseUrl: "https://login.apne2.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "aps1",
    name: "Asia Pacific (Mumbai)",
    domain: "aps1.pure.cloud",
    applicationUrl: "https://apps.aps1.pure.cloud",
    apiBaseUrl: "https://api.aps1.pure.cloud",
    authBaseUrl: "https://login.aps1.pure.cloud",
    defaultApplicationUrl: "https://apps.aps1.pure.cloud",
    defaultApiBaseUrl: "https://api.aps1.pure.cloud",
    defaultAuthBaseUrl: "https://login.aps1.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "apne3",
    name: "Asia Pacific (Osaka)",
    domain: "apne3.pure.cloud",
    applicationUrl: "https://apps.apne3.pure.cloud",
    apiBaseUrl: "https://api.apne3.pure.cloud",
    authBaseUrl: "https://login.apne3.pure.cloud",
    defaultApplicationUrl: "https://apps.apne3.pure.cloud",
    defaultApiBaseUrl: "https://api.apne3.pure.cloud",
    defaultAuthBaseUrl: "https://login.apne3.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "euw1",
    name: "EMEA (Ireland / Dublin)",
    domain: "mypurecloud.ie",
    applicationUrl: "https://apps.mypurecloud.ie",
    apiBaseUrl: "https://api.mypurecloud.ie",
    authBaseUrl: "https://login.mypurecloud.ie",
    defaultApplicationUrl: "https://apps.mypurecloud.ie",
    defaultApiBaseUrl: "https://api.mypurecloud.ie",
    defaultAuthBaseUrl: "https://login.mypurecloud.ie",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "euc1",
    name: "EMEA (Frankfurt)",
    domain: "mypurecloud.de",
    applicationUrl: "https://apps.mypurecloud.de",
    apiBaseUrl: "https://api.mypurecloud.de",
    authBaseUrl: "https://login.mypurecloud.de",
    defaultApplicationUrl: "https://apps.mypurecloud.de",
    defaultApiBaseUrl: "https://api.mypurecloud.de",
    defaultAuthBaseUrl: "https://login.mypurecloud.de",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "euw2",
    name: "EMEA (London)",
    domain: "euw2.pure.cloud",
    applicationUrl: "https://apps.euw2.pure.cloud",
    apiBaseUrl: "https://api.euw2.pure.cloud",
    authBaseUrl: "https://login.euw2.pure.cloud",
    defaultApplicationUrl: "https://apps.euw2.pure.cloud",
    defaultApiBaseUrl: "https://api.euw2.pure.cloud",
    defaultAuthBaseUrl: "https://login.euw2.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "euc2",
    name: "EMEA (Zurich)",
    domain: "euc2.pure.cloud",
    applicationUrl: "https://apps.euc2.pure.cloud",
    apiBaseUrl: "https://api.euc2.pure.cloud",
    authBaseUrl: "https://login.euc2.pure.cloud",
    defaultApplicationUrl: "https://apps.euc2.pure.cloud",
    defaultApiBaseUrl: "https://api.euc2.pure.cloud",
    defaultAuthBaseUrl: "https://login.euc2.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "mec1",
    name: "Middle East (UAE)",
    domain: "mec1.pure.cloud",
    applicationUrl: "https://apps.mec1.pure.cloud",
    apiBaseUrl: "https://api.mec1.pure.cloud",
    authBaseUrl: "https://login.mec1.pure.cloud",
    defaultApplicationUrl: "https://apps.mec1.pure.cloud",
    defaultApiBaseUrl: "https://api.mec1.pure.cloud",
    defaultAuthBaseUrl: "https://login.mec1.pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "use2-fedramp",
    name: "Americas (US East 2 - FedRAMP)",
    domain: "use2.us-gov-pure.cloud",
    applicationUrl: "https://apps.use2.us-gov-pure.cloud",
    apiBaseUrl: "https://api.use2.us-gov-pure.cloud",
    authBaseUrl: "https://login.use2.us-gov-pure.cloud",
    defaultApplicationUrl: "https://apps.use2.us-gov-pure.cloud",
    defaultApiBaseUrl: "https://api.use2.us-gov-pure.cloud",
    defaultAuthBaseUrl: "https://login.use2.us-gov-pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  },
  {
    id: "edee1",
    name: "European Sovereign Region (Germany)",
    domain: "edee1.eusc-pure.cloud",
    applicationUrl: "https://apps.edee1.eusc-pure.cloud",
    apiBaseUrl: "https://api.edee1.eusc-pure.cloud",
    authBaseUrl: "https://login.edee1.eusc-pure.cloud",
    defaultApplicationUrl: "https://apps.edee1.eusc-pure.cloud",
    defaultApiBaseUrl: "https://api.edee1.eusc-pure.cloud",
    defaultAuthBaseUrl: "https://login.edee1.eusc-pure.cloud",
    systemRegion: true,
    enabled: true,
    modified: false,
    createdAt: now,
    updatedAt: now,
    updatedBy: ""
  }
];
